#!/usr/bin/env python3
# Paper 27 reproducibility - regenerate Tables 2 and 3 from feasibility.json outputs.
# License: Apache-2.0
# Usage: python3 reproduce_tables.py [--manifest manifest.yaml] [--verify-checksums]
#
# Reads each per-regime feasibility.json file listed in manifest.yaml, applies
# the paper's governance-evidence score (F=1.0, P=0.5, S=0.0, O=0.0), and prints
# Table 2 (per-property by per-regime matrix with completeness percentage) and
# Table 3 (per-property dispersion across the six vendor SDK regimes only).
# Table 1 (per-regime worked-example anchor inventory) is in section 4 of the
# manuscript and is not regenerated by this script; see manifest.yaml regimes:
#
# When --verify-checksums is passed, every feasibility.json file is hashed
# (SHA-256) before parsing and the result is compared to manifest.yaml
# feasibility_outputs.<column>.sha256. Any mismatch aborts before printing.

from __future__ import annotations

import argparse
import hashlib
import json
import math
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write(
        "PyYAML not installed. Run: python3 -m pip install pyyaml\n"
    )
    sys.exit(1)

# Internal property keys (match the Decision Event Schema feasibility.json field).
PROPERTIES = [
    "inputs",
    "policy_basis",
    "operator_identity",
    "authorization_envelope",
    "reasoning_trace",
    "output_action",
    "post_condition_state",
]

# Manuscript-facing property display labels (match §5 Tables 2 and 3 row names).
PROPERTY_DISPLAY_LABEL = {
    "inputs": "inputs",
    "policy_basis": "policy basis",
    "operator_identity": "operator identity",
    "authorization_envelope": "authorization envelope",
    "reasoning_trace": "reasoning trace",
    "output_action": "output action",
    "post_condition_state": "post-condition state",
}

CATEGORY_LETTER = {
    "fully_fillable": "F",
    "partially_fillable": "P",
    "structurally_unfillable": "S",
    "opaque": "O",
}

# Strict governance score (paper convention): O treated as zero.
SCORE = {"F": 1.0, "P": 0.5, "S": 0.0, "O": 0.0}

VENDOR_REGIMES = ["bedrock", "langsmith", "anthropic", "openai_agents", "otlp", "mcp"]


def load_feasibility(path: Path) -> dict[str, str]:
    """Return {property_name: category_letter} for a single feasibility.json."""
    with path.open() as fh:
        report = json.load(fh)
    out: dict[str, str] = {}
    for entry in report.get("per_property", []):
        prop = entry["property"]
        cat = CATEGORY_LETTER[entry["category"]]
        out[prop] = cat
    missing = [p for p in PROPERTIES if p not in out]
    if missing:
        raise ValueError(f"{path}: missing properties {missing}")
    return out


def sha256_of(path: Path) -> str:
    """Return lowercase hex SHA-256 of the file at path, streaming."""
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def population_cv(values: list[float]) -> float | None:
    """Return population CV, or None when the mean is zero (CV undefined).

    Note: 0/0 is mathematically undefined. We return None so the caller can
    render the cell as "N/A (mean = 0)" rather than 0.00.
    """
    n = len(values)
    if n == 0:
        return None
    mean = sum(values) / n
    if mean == 0:
        return None
    var = sum((v - mean) ** 2 for v in values) / n
    return math.sqrt(var) / mean


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--manifest",
        default=str(Path(__file__).parent / "manifest.yaml"),
        help="Path to the reproducibility manifest YAML",
    )
    parser.add_argument(
        "--paper-root",
        default=str(Path(__file__).resolve().parent),
        help=(
            "Repository root directory holding manifest.yaml and the data/ tree "
            "(default: directory containing this script)."
        ),
    )
    parser.add_argument(
        "--verify-checksums",
        action="store_true",
        help=(
            "Verify SHA-256 of every feasibility.json against the value pinned "
            "in manifest.yaml feasibility_outputs.<column>.sha256 before parsing. "
            "Any mismatch aborts with exit code 2 before any table is printed."
        ),
    )
    args = parser.parse_args()

    manifest = yaml.safe_load(Path(args.manifest).read_text())
    paper_root = Path(args.paper_root)
    feasibility_outputs = manifest["feasibility_outputs"]

    # Map manifest column names to the columns shown in the paper.
    column_order = [
        ("bedrock", "Bedrock"),
        ("langsmith", "LangSmith"),
        ("anthropic", "Anthropic"),
        ("openai_agents", "OpenAI"),
        ("otlp", "OTLP-Vertex"),
        ("mcp", "MCP"),
        ("oep_canonical", "OEP"),
        ("replit_drop_database", "Replit incident"),
    ]

    matrix: dict[str, dict[str, str]] = {}
    for key, label in column_order:
        entry = feasibility_outputs[key]
        # Manifest revision 4: feasibility_outputs entries are objects with
        # `path` and `sha256` keys. Fall back to bare-string for backward
        # compatibility with manifest revision 3.
        if isinstance(entry, dict):
            rel_path = entry["path"]
            pinned_sha256 = entry.get("sha256")
        else:
            rel_path = entry
            pinned_sha256 = None
        full_path = paper_root / rel_path
        if args.verify_checksums:
            if pinned_sha256 is None:
                sys.stderr.write(
                    f"--verify-checksums: manifest entry for {key!r} has no sha256 "
                    f"field; cannot verify {full_path}.\n"
                )
                return 2
            actual = sha256_of(full_path)
            if actual != pinned_sha256:
                sys.stderr.write(
                    f"--verify-checksums: SHA-256 mismatch for {full_path}\n"
                    f"  pinned:   {pinned_sha256}\n"
                    f"  computed: {actual}\n"
                )
                return 2
        matrix[label] = load_feasibility(full_path)

    if args.verify_checksums:
        sys.stderr.write(
            f"--verify-checksums: all {len(column_order)} feasibility.json files "
            f"match manifest pins.\n"
        )

    # ---- Table 2 (matrix) ----
    print("Table 2. Per-property by per-regime reconstructability matrix at anchor scale (n=1 per cell).")
    print("Letter codes: F (fully fillable), P (partially fillable), S (structurally unfillable), O (opaque).")
    print("The strict-governance-completeness pct row uses the strict governance score F=1.0, P=0.5, S=0.0, O=0.0 averaged over the seven property classes per column. The label distinguishes this paper's score from DTR's native completeness_pct field, which treats opaque as evidenced.")
    print()
    header = "| Property | " + " | ".join(label for _, label in column_order) + " |"
    print(header)
    print("|" + "|".join("---" for _ in range(len(column_order) + 1)) + "|")
    for prop in PROPERTIES:
        row = "| " + PROPERTY_DISPLAY_LABEL[prop] + " | " + " | ".join(matrix[label][prop] for _, label in column_order) + " |"
        print(row)
    completeness_row = ["| **strict-governance-completeness pct** |"]
    for _, label in column_order:
        scores = [SCORE[matrix[label][p]] for p in PROPERTIES]
        pct = round(sum(scores) / len(PROPERTIES) * 100, 1)
        completeness_row.append(f" **{pct:.1f}** |")
    print("".join(completeness_row))

    # ---- Table 3 (strict-score descriptive summary) ----
    # Per minor revision: CV is reported as a secondary descriptive summary.
    # The categorical pattern in Table 2 is the primary finding; Table 3
    # collapses the six vendor-regime cells per property to a scalar mean
    # and population CV under the strict governance score.
    print()
    print("Table 3. Strict-score descriptive summary across the six vendor SDK regimes.")
    print("Per-property category counts (F/P/S/O) over the six vendor-regime columns are the primary categorical view; mean and CV are secondary scalar summaries under the strict governance score F=1.0, P=0.5, S=0.0, O=0.0.")
    print("CV = population standard deviation divided by mean (n=6 denominator; not n-1).")
    print("A different non-compensatory scoring rule could change the scalar summaries (mean, CV) without changing the categorical category-count columns.")
    print()
    print("| Property | F | P | S | O | Mean (vendor regimes only) | CV across regimes |")
    print("|---|---|---|---|---|---|---|")
    vendor_labels = [label for key, label in column_order if key in VENDOR_REGIMES]
    for prop in PROPERTIES:
        cats = [matrix[label][prop] for label in vendor_labels]
        f_count = cats.count("F")
        p_count = cats.count("P")
        s_count = cats.count("S")
        o_count = cats.count("O")
        vals = [SCORE[c] for c in cats]
        mean = sum(vals) / len(vals)
        cv = population_cv(vals)
        cv_str = "N/A (mean = 0)" if cv is None else f"{cv:.2f}"
        print(
            f"| {PROPERTY_DISPLAY_LABEL[prop]} | {f_count} | {p_count} | "
            f"{s_count} | {o_count} | {mean:.2f} | {cv_str} |"
        )

    return 0


if __name__ == "__main__":
    sys.exit(main())
